# Welcome to Jekyll!

title: MrC Jekyll Project Page Test
email: #your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Base Jekyll Image, installed as gh-pages branch with no external build.
baseurl: "/Jekyll-Demo" # the subpath of your site, e.g. /blog
url: "https://www.mrcozzens.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# AC FIX PERMALINK ON GH-PAGES SET DEFAULTS
defaults:
-
   scope:
     path: ""
     type: "posts"
   values:
     permalink: /:year/:month/:title.html # change permalink structure with articles in front.

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
